### ISSUE TITLE
Wrong structure

### ISSUE THREAD

**Issue by marufjs** [SinthujanBalachandran/whatsapp-clone2#1]
I would suggest you to create a folder 📁 name img or image or assets and put all the images. On that folder. Similarly If you have multiple css file you need to create a folder named css and put your all css files there. 
Anyway nice work.

**Comment by SinthujanBalachandran** [comment]
Thanks for the tipsSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Maruf ***@***.***> Date: 06/09/2021  1:36 a.m.  (GMT+05:30) To: SinthujanBalachandran/whatsapp-clone2 ***@***.***> Cc: Subscribed ***@***.***> Subject: [SinthujanBalachandran/whatsapp-clone2] Wrong structure (#1) 

I would suggest you to create a folder 📁 name img or image or assets and put all the images. On that folder. Similarly If you have multiple css file you need to create a folder named css and put your all css files there.

Anyway nice work.



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.



[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/SinthujanBalachandran/whatsapp-clone2/issues/1",

"url": "https://github.com/SinthujanBalachandran/whatsapp-clone2/issues/1",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by marufjs** [comment]
Welcome
